#!/bin/bash


if [ "$SKIP_PRECOMMIT_CHECKS" = true ] || [ "$SKIP_PRECOMMIT_CHECKS" = 1 ] ; then
    echo "=== Skipping pre-commit prettier run ==="
    exit 0
fi

ROOT_DIR=$(git rev-parse --show-toplevel)

# Select staged files.
FILES="$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')"
[ -z "$FILES" ] && echo "=== Nothing to do ===" && exit 0


echo "======================"
echo "=== Running linter ==="
echo "======================"

MIDDLEWARE_FILES="$(echo "$FILES" | grep -E "src/middleware" | xargs realpath)"
FRONTEND_FILES="$(echo "$FILES" | grep -E "src/frontend" | xargs realpath)"

LINT_FILE_TYPES="js|jsx|ts|tsx"
LINT_MIDDLEWARE_FILES=$(echo "$MIDDLEWARE_FILES" | grep -E "\.($LINT_FILE_TYPES)$")
LINT_FRONTEND_FILES=$(echo "$FRONTEND_FILES" | grep -E "\.($LINT_FILE_TYPES)$")

# Function to evaluate the linter results
function evaluate_linter_results {
    if [ $? == 1 ]; then
        echo "================================================================="
        echo "The linter found some errors. Please fix them before committing."
        echo "You can skip pre-commit checks by setting \$SKIP_PRECOMMIT_CHECKS"
        echo "================================================================="
        exit 1
    elif [ $? -ge 2 ]; then
        echo "==============================================================================="
        echo "Something went wrong running the linter. Have you bootstrapped the project yet?"
        echo "You can skip pre-commit checks by setting \$SKIP_PRECOMMIT_CHECKS"
        echo "==============================================================================="
        exit 1
    fi
}

cd "$ROOT_DIR"/src/middleware
yarn run lint-files $LINT_MIDDLEWARE_FILES
evaluate_linter_results

cd "$ROOT_DIR"/src/frontend
yarn run lint-files $LINT_FRONTEND_FILES
evaluate_linter_results

cd "$ROOT_DIR"


echo "========================"
echo "=== Running prettier ==="
echo "========================"

# Run prettier on all staged files.
echo "$FILES" | xargs npx prettier --write --ignore-unknown

if [ $? != 0 ]; then
    echo "========================================================================"
    echo "Something went wrong running prettier. Have you run \`npm install\` yet?"
    echo "You can skip pre-commit checks by setting \$SKIP_PRECOMMIT_CHECKS"
    echo "========================================================================"
    exit 1
fi

echo "=== Prettier done ==="

# Add back the modified/prettified files to staging
xargs git add "$FILES"

exit 0
