#!/bin/bash

# This script runs the linter and prettier for staged files
# in the middleware and frontend packages.


# Skip, if flag is set.
if [ "$SKIP_PRECOMMIT_CHECKS" = true ] || [ "$SKIP_PRECOMMIT_CHECKS" = 1 ] ; then
    echo "=== Skipping pre-commit prettier run ==="
    exit 0
fi

# cd to root directory.
ROOT_DIR=$(git rev-parse --show-toplevel)
cd "$ROOT_DIR"


# Select staged files.
FILES="$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | xargs -r realpath | sed 's/.*/"&"/')"
[ -z "$FILES" ] && echo "=== Nothing to do ===" && exit 0

## Run scripts

./scripts/run-linter.sh $FILES
if [ $? != 0 ]; then
    exit $?
fi

./scripts/run-prettier.sh $FILES
if [ $? != 0 ]; then
    exit $?
fi


# Add back the modified/prettified files to staging
echo "$FILES" | xargs -r git add

exit 0
