version: '3.5'
services:
  fuseki_tests:
    build:
      context: ./src/jena/fuseki-docker
      dockerfile: Dockerfile
    container_name: fuseki_tests
    restart: always
    volumes:
      - rdf_data:/fuseki
      - staging:/staging
    ports:
      - "3040:3030"
    expose:
      - "3040"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

volumes:
  rdf_data:
  staging:
networks:
  semapps:
    name: semapps_network
