const { SUPPORTED_MIME_TYPES } = require('@semapps/mime-negotiation');

const SUPPORTED_ACCEPT_MIME_TYPES = {
  JSON: SUPPORTED_MIME_TYPES.JSON,
  TURTLE: SUPPORTED_MIME_TYPES.TURTLE,
  TRIPLE: SUPPORTED_MIME_TYPES.TRIPLE
};
const SUPPORTED_CONTENT_MIME_TYPES = {
  JSON: SUPPORTED_MIME_TYPES.JSON,
  TURTLE: SUPPORTED_MIME_TYPES.TURTLE,
  TRIPLE: SUPPORTED_MIME_TYPES.TRIPLE
};

module.exports = {
  SUPPORTED_ACCEPT_MIME_TYPES,
  SUPPORTED_CONTENT_MIME_TYPES
};
