import mp from './mp.json' with { type: 'json' };
import oasis from './oasis.json' with { type: 'json' };
import og from './og.json' with { type: 'json' };
import pair from './pair.json' with { type: 'json' };
import petr from './petr.json' with { type: 'json' };
import schema from './schema.json' with { type: 'json' };
import skos from './skos.json' with { type: 'json' };
import syreen from './syreen.json' with { type: 'json' };
import tutor from './tutor.json' with { type: 'json' };
export { mp, oasis, og, pair, petr, schema, skos, syreen, tutor };
