version: '3.5'
services:
  solid:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: solid
    restart: always
    environment:
        - CONFIG_URL=https://assemblee-virtuelle.gitlab.io/semappsconfig/local.json
    volumes:
      - .:/main/
    networks:
      - semapps
    ports:
      - "8080:8080"
      - "3000:3000"
    expose:
      - "8080"
      - "3000"
    command: npm run dev
volumes:
  data:

networks:
  semapps:
    name: semapps_network
