name: website_deploy
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19.0.1+1
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
#         now-args: '--prod' # Optional
          vercel-org-id: 'team_Lirf6L6BdNRARtO7mBp1uBct'
          vercel-project-id: 'QmaojiX3jHJAaqREDhmSeBm1omBWzg8YNDB923pQwtPCe1'
          working-directory: ./website
          scope: 'semapps'
